#!/bin/bash
PATH="/usr/local/bin:$PATH"
chmod +x "/Users/rick/Downloads/HISE-develop-4/tools/Projucer/Projucer.app/Contents/MacOS/Projucer"
cd "`dirname "$0"`"
"/Users/rick/Downloads/HISE-develop-4/tools/Projucer/Projucer.app/Contents/MacOS/Projucer" --resave AutogeneratedProject.jucer

set -o pipefail
echo Compiling  Smut ...
xcodebuild -project "Builds/MacOSX/Smut.xcodeproj" -configuration "Release" -jobs "6" | "/Users/rick/Downloads/HISE-develop-4/tools/Projucer/xcbeautify"
