/** Autogenerated Main.cpp. */

// ===============================| Include only the DSP files  |===============================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// =========================| Now we can add the rest of the codebase |=========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =====================================| Project Factory |=====================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -----------------------------------------------------------------
		
		registerPolyNode<project::shfiter<1>, project::shfiter<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::psfine<1>, project::psfine<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::ps2<1>, project::ps2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::klp2<1>, project::klp2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::klp<1>, project::klp<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::khp2<1>, project::khp2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::khp<1>, project::khp<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::hole<1>, scriptnode::wrap::illegal_poly<project::hole<1>>>();
		registerPolyNode<project::gran<1>, scriptnode::wrap::illegal_poly<project::gran<1>>>();
		registerPolyNode<project::Comb<1>, project::Comb<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::lfo<1>, wrap::illegal_poly<project::lfo<1>>>();
		registerPolyNode<project::osc1<1>, project::osc1<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::verb<1>, wrap::illegal_poly<project::verb<1>>>();
		registerDataNode<project::empty_networkdata>();
		registerDataNode<project::GainMod_networkdata>();
		registerDataNode<project::lfo2_networkdata>();
		registerDataNode<project::lfo3_networkdata>();
		registerDataNode<project::lfo4_networkdata>();
		registerDataNode<project::Lfos_networkdata>();
		registerDataNode<project::ModConnect_networkdata>();
		registerDataNode<project::SuperDetune_networkdata>();
		registerDataNode<project::VcaAdsr_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


