/** Autogenerated Main.cpp. */

// ===========================| Include only the DSP files  |===========================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// =====================| Now we can add the rest of the codebase |=====================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =================================| Project Factory |=================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ---------------------------------------------------------
		
		registerPolyNode<project::Env<1>, project::Env<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::LfoNew<1>, wrap::illegal_poly<project::LfoNew<1>>>();
		registerPolyNode<project::Sm2<1>, project::Sm2<NUM_POLYPHONIC_VOICES>>();
		registerDataNode<project::combValueTest_networkdata>();
		registerDataNode<project::empty_networkdata>();
		registerDataNode<project::FoldTests_networkdata>();
		registerDataNode<project::GainMod_networkdata>();
		registerDataNode<project::lfo_networkdata>();
		registerDataNode<project::lfo2_networkdata>();
		registerDataNode<project::lfo3_networkdata>();
		registerDataNode<project::lfo4_networkdata>();
		registerDataNode<project::Lfos_networkdata>();
		registerDataNode<project::ModConnect_networkdata>();
		registerDataNode<project::mp_networkdata>();
		registerDataNode<project::pitch_networkdata>();
		registerDataNode<project::PitchTempo_networkdata>();
		registerDataNode<project::Revern_networkdata>();
		registerDataNode<project::rp_networkdata>();
		registerDataNode<project::SuperDetune_networkdata>();
		registerDataNode<project::VcaAdsr_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


