/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files ------------------

#include "combValueTest_networkdata.h"
#include "empty_networkdata.h"
#include "Env.h"
#include "FoldTests_networkdata.h"
#include "GainMod_networkdata.h"
#include "lfo2_networkdata.h"
#include "lfo3_networkdata.h"
#include "lfo4_networkdata.h"
#include "LfoNew.h"
#include "Lfos_networkdata.h"
#include "lfo_networkdata.h"
#include "ModConnect_networkdata.h"
#include "mp_networkdata.h"
#include "PitchTempo_networkdata.h"
#include "pitch_networkdata.h"
#include "Revern_networkdata.h"
#include "rp_networkdata.h"
#include "Sm2.h"
#include "SuperDetune_networkdata.h"
#include "VcaAdsr_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

