/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "Comb.h"
#include "gran.h"
#include "hole.h"
#include "khp.h"
#include "khp2.h"
#include "klp.h"
#include "klp2.h"
#include "ps2.h"
#include "psfine.h"
#include "shfiter.h"

// Include compiled network files ------------------

#include "empty_networkdata.h"
#include "GainMod_networkdata.h"
#include "lfo.h"
#include "lfo2_networkdata.h"
#include "lfo3_networkdata.h"
#include "lfo4_networkdata.h"
#include "Lfos_networkdata.h"
#include "osc1.h"
#include "SuperDetune_networkdata.h"
#include "VcaAdsr_networkdata.h"
#include "verb.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

